typedef enum
{
    G_AWESOME_CODE_fa_500px = 0xf26e,
    G_AWESOME_CODE_addressbook = 0xf2b9,
    G_AWESOME_CODE_addressbooko = 0xf2ba,
    G_AWESOME_CODE_addresscard = 0xf2bb,
    G_AWESOME_CODE_addresscardo = 0xf2bc,
    G_AWESOME_CODE_adjust = 0xf042,
    G_AWESOME_CODE_adn = 0xf170,
    G_AWESOME_CODE_aligncenter = 0xf037,
    G_AWESOME_CODE_alignjustify = 0xf039,
    G_AWESOME_CODE_alignleft = 0xf036,
    G_AWESOME_CODE_alignright = 0xf038,
    G_AWESOME_CODE_amazon = 0xf270,
    G_AWESOME_CODE_ambulance = 0xf0f9,
    G_AWESOME_CODE_americansignlanguageinterpreting = 0xf2a3,
    G_AWESOME_CODE_anchor = 0xf13d,
    G_AWESOME_CODE_android = 0xf17b,
    G_AWESOME_CODE_angellist = 0xf209,
    G_AWESOME_CODE_angledoubledown = 0xf103,
    G_AWESOME_CODE_angledoubleleft = 0xf100,
    G_AWESOME_CODE_angledoubleright = 0xf101,
    G_AWESOME_CODE_angledoubleup = 0xf102,
    G_AWESOME_CODE_angledown = 0xf107,
    G_AWESOME_CODE_angleleft = 0xf104,
    G_AWESOME_CODE_angleright = 0xf105,
    G_AWESOME_CODE_angleup = 0xf106,
    G_AWESOME_CODE_apple = 0xf179,
    G_AWESOME_CODE_archive = 0xf187,
    G_AWESOME_CODE_areachart = 0xf1fe,
    G_AWESOME_CODE_arrowcircledown = 0xf0ab,
    G_AWESOME_CODE_arrowcircleleft = 0xf0a8,
    G_AWESOME_CODE_arrowcircleodown = 0xf01a,
    G_AWESOME_CODE_arrowcircleoleft = 0xf190,
    G_AWESOME_CODE_arrowcircleoright = 0xf18e,
    G_AWESOME_CODE_arrowcircleoup = 0xf01b,
    G_AWESOME_CODE_arrowcircleright = 0xf0a9,
    G_AWESOME_CODE_arrowcircleup = 0xf0aa,
    G_AWESOME_CODE_arrowdown = 0xf063,
    G_AWESOME_CODE_arrowleft = 0xf060,
    G_AWESOME_CODE_arrowright = 0xf061,
    G_AWESOME_CODE_arrowup = 0xf062,
    G_AWESOME_CODE_arrows = 0xf047,
    G_AWESOME_CODE_arrowsalt = 0xf0b2,
    G_AWESOME_CODE_arrowsh = 0xf07e,
    G_AWESOME_CODE_arrowsv = 0xf07d,
    G_AWESOME_CODE_aslinterpreting = 0xf2a3,
    G_AWESOME_CODE_assistivelisteningsystems = 0xf2a2,
    G_AWESOME_CODE_asterisk = 0xf069,
    G_AWESOME_CODE_at = 0xf1fa,
    G_AWESOME_CODE_audiodescription = 0xf29e,
    G_AWESOME_CODE_automobile = 0xf1b9,
    G_AWESOME_CODE_backward = 0xf04a,
    G_AWESOME_CODE_balancescale = 0xf24e,
    G_AWESOME_CODE_ban = 0xf05e,
    G_AWESOME_CODE_bandcamp = 0xf2d5,
    G_AWESOME_CODE_bank = 0xf19c,
    G_AWESOME_CODE_barchart = 0xf080,
    G_AWESOME_CODE_barcharto = 0xf080,
    G_AWESOME_CODE_barcode = 0xf02a,
    G_AWESOME_CODE_bars = 0xf0c9,
    G_AWESOME_CODE_bath = 0xf2cd,
    G_AWESOME_CODE_bathtub = 0xf2cd,
    G_AWESOME_CODE_battery = 0xf240,
    G_AWESOME_CODE_battery0 = 0xf244,
    G_AWESOME_CODE_battery1 = 0xf243,
    G_AWESOME_CODE_battery2 = 0xf242,
    G_AWESOME_CODE_battery3 = 0xf241,
    G_AWESOME_CODE_battery4 = 0xf240,
    G_AWESOME_CODE_batteryempty = 0xf244,
    G_AWESOME_CODE_batteryfull = 0xf240,
    G_AWESOME_CODE_batteryhalf = 0xf242,
    G_AWESOME_CODE_batteryquarter = 0xf243,
    G_AWESOME_CODE_batterythreequarters = 0xf241,
    G_AWESOME_CODE_bed = 0xf236,
    G_AWESOME_CODE_beer = 0xf0fc,
    G_AWESOME_CODE_behance = 0xf1b4,
    G_AWESOME_CODE_behancesquare = 0xf1b5,
    G_AWESOME_CODE_bell = 0xf0f3,
    G_AWESOME_CODE_bello = 0xf0a2,
    G_AWESOME_CODE_bellslash = 0xf1f6,
    G_AWESOME_CODE_bellslasho = 0xf1f7,
    G_AWESOME_CODE_bicycle = 0xf206,
    G_AWESOME_CODE_binoculars = 0xf1e5,
    G_AWESOME_CODE_birthdaycake = 0xf1fd,
    G_AWESOME_CODE_bitbucket = 0xf171,
    G_AWESOME_CODE_bitbucketsquare = 0xf172,
    G_AWESOME_CODE_bitcoin = 0xf15a,
    G_AWESOME_CODE_blacktie = 0xf27e,
    G_AWESOME_CODE_blind = 0xf29d,
    G_AWESOME_CODE_bluetooth = 0xf293,
    G_AWESOME_CODE_bluetoothb = 0xf294,
    G_AWESOME_CODE_bold = 0xf032,
    G_AWESOME_CODE_bolt = 0xf0e7,
    G_AWESOME_CODE_bomb = 0xf1e2,
    G_AWESOME_CODE_book = 0xf02d,
    G_AWESOME_CODE_bookmark = 0xf02e,
    G_AWESOME_CODE_bookmarko = 0xf097,
    G_AWESOME_CODE_braille = 0xf2a1,
    G_AWESOME_CODE_briefcase = 0xf0b1,
    G_AWESOME_CODE_btc = 0xf15a,
    G_AWESOME_CODE_bug = 0xf188,
    G_AWESOME_CODE_building = 0xf1ad,
    G_AWESOME_CODE_buildingo = 0xf0f7,
    G_AWESOME_CODE_bullhorn = 0xf0a1,
    G_AWESOME_CODE_bullseye = 0xf140,
    G_AWESOME_CODE_bus = 0xf207,
    G_AWESOME_CODE_buysellads = 0xf20d,
    G_AWESOME_CODE_cab = 0xf1ba,
    G_AWESOME_CODE_calculator = 0xf1ec,
    G_AWESOME_CODE_calendar = 0xf073,
    G_AWESOME_CODE_calendarchecko = 0xf274,
    G_AWESOME_CODE_calendarminuso = 0xf272,
    G_AWESOME_CODE_calendaro = 0xf133,
    G_AWESOME_CODE_calendarpluso = 0xf271,
    G_AWESOME_CODE_calendartimeso = 0xf273,
    G_AWESOME_CODE_camera = 0xf030,
    G_AWESOME_CODE_cameraretro = 0xf083,
    G_AWESOME_CODE_car = 0xf1b9,
    G_AWESOME_CODE_caretdown = 0xf0d7,
    G_AWESOME_CODE_caretleft = 0xf0d9,
    G_AWESOME_CODE_caretright = 0xf0da,
    G_AWESOME_CODE_caretsquareodown = 0xf150,
    G_AWESOME_CODE_caretsquareoleft = 0xf191,
    G_AWESOME_CODE_caretsquareoright = 0xf152,
    G_AWESOME_CODE_caretsquareoup = 0xf151,
    G_AWESOME_CODE_caretup = 0xf0d8,
    G_AWESOME_CODE_cartarrowdown = 0xf218,
    G_AWESOME_CODE_cartplus = 0xf217,
    G_AWESOME_CODE_cc = 0xf20a,
    G_AWESOME_CODE_ccamex = 0xf1f3,
    G_AWESOME_CODE_ccdinersclub = 0xf24c,
    G_AWESOME_CODE_ccdiscover = 0xf1f2,
    G_AWESOME_CODE_ccjcb = 0xf24b,
    G_AWESOME_CODE_ccmastercard = 0xf1f1,
    G_AWESOME_CODE_ccpaypal = 0xf1f4,
    G_AWESOME_CODE_ccstripe = 0xf1f5,
    G_AWESOME_CODE_ccvisa = 0xf1f0,
    G_AWESOME_CODE_certificate = 0xf0a3,
    G_AWESOME_CODE_chain = 0xf0c1,
    G_AWESOME_CODE_chainbroken = 0xf127,
    G_AWESOME_CODE_check = 0xf00c,
    G_AWESOME_CODE_checkcircle = 0xf058,
    G_AWESOME_CODE_checkcircleo = 0xf05d,
    G_AWESOME_CODE_checksquare = 0xf14a,
    G_AWESOME_CODE_checksquareo = 0xf046,
    G_AWESOME_CODE_chevroncircledown = 0xf13a,
    G_AWESOME_CODE_chevroncircleleft = 0xf137,
    G_AWESOME_CODE_chevroncircleright = 0xf138,
    G_AWESOME_CODE_chevroncircleup = 0xf139,
    G_AWESOME_CODE_chevrondown = 0xf078,
    G_AWESOME_CODE_chevronleft = 0xf053,
    G_AWESOME_CODE_chevronright = 0xf054,
    G_AWESOME_CODE_chevronup = 0xf077,
    G_AWESOME_CODE_child = 0xf1ae,
    G_AWESOME_CODE_chrome = 0xf268,
    G_AWESOME_CODE_circle = 0xf111,
    G_AWESOME_CODE_circleo = 0xf10c,
    G_AWESOME_CODE_circleonotch = 0xf1ce,
    G_AWESOME_CODE_circlethin = 0xf1db,
    G_AWESOME_CODE_clipboard = 0xf0ea,
    G_AWESOME_CODE_clocko = 0xf017,
    G_AWESOME_CODE_clone = 0xf24d,
    G_AWESOME_CODE_close = 0xf00d,
    G_AWESOME_CODE_cloud = 0xf0c2,
    G_AWESOME_CODE_clouddownload = 0xf0ed,
    G_AWESOME_CODE_cloudupload = 0xf0ee,
    G_AWESOME_CODE_cny = 0xf157,
    G_AWESOME_CODE_code = 0xf121,
    G_AWESOME_CODE_codefork = 0xf126,
    G_AWESOME_CODE_codepen = 0xf1cb,
    G_AWESOME_CODE_codiepie = 0xf284,
    G_AWESOME_CODE_coffee = 0xf0f4,
    G_AWESOME_CODE_cog = 0xf013,
    G_AWESOME_CODE_cogs = 0xf085,
    G_AWESOME_CODE_columns = 0xf0db,
    G_AWESOME_CODE_comment = 0xf075,
    G_AWESOME_CODE_commento = 0xf0e5,
    G_AWESOME_CODE_commenting = 0xf27a,
    G_AWESOME_CODE_commentingo = 0xf27b,
    G_AWESOME_CODE_comments = 0xf086,
    G_AWESOME_CODE_commentso = 0xf0e6,
    G_AWESOME_CODE_compass = 0xf14e,
    G_AWESOME_CODE_compress = 0xf066,
    G_AWESOME_CODE_connectdevelop = 0xf20e,
    G_AWESOME_CODE_contao = 0xf26d,
    G_AWESOME_CODE_copy = 0xf0c5,
    G_AWESOME_CODE_copyright = 0xf1f9,
    G_AWESOME_CODE_creativecommons = 0xf25e,
    G_AWESOME_CODE_creditcard = 0xf09d,
    G_AWESOME_CODE_creditcardalt = 0xf283,
    G_AWESOME_CODE_crop = 0xf125,
    G_AWESOME_CODE_crosshairs = 0xf05b,
    G_AWESOME_CODE_css3 = 0xf13c,
    G_AWESOME_CODE_cube = 0xf1b2,
    G_AWESOME_CODE_cubes = 0xf1b3,
    G_AWESOME_CODE_cut = 0xf0c4,
    G_AWESOME_CODE_cutlery = 0xf0f5,
    G_AWESOME_CODE_dashboard = 0xf0e4,
    G_AWESOME_CODE_dashcube = 0xf210,
    G_AWESOME_CODE_database = 0xf1c0,
    G_AWESOME_CODE_deaf = 0xf2a4,
    G_AWESOME_CODE_deafness = 0xf2a4,
    G_AWESOME_CODE_dedent = 0xf03b,
    G_AWESOME_CODE_delicious = 0xf1a5,
    G_AWESOME_CODE_desktop = 0xf108,
    G_AWESOME_CODE_deviantart = 0xf1bd,
    G_AWESOME_CODE_diamond = 0xf219,
    G_AWESOME_CODE_digg = 0xf1a6,
    G_AWESOME_CODE_dollar = 0xf155,
    G_AWESOME_CODE_dotcircleo = 0xf192,
    G_AWESOME_CODE_download = 0xf019,
    G_AWESOME_CODE_dribbble = 0xf17d,
    G_AWESOME_CODE_driverslicense = 0xf2c2,
    G_AWESOME_CODE_driverslicenseo = 0xf2c3,
    G_AWESOME_CODE_dropbox = 0xf16b,
    G_AWESOME_CODE_drupal = 0xf1a9,
    G_AWESOME_CODE_edge = 0xf282,
    G_AWESOME_CODE_edit = 0xf044,
    G_AWESOME_CODE_eercast = 0xf2da,
    G_AWESOME_CODE_eject = 0xf052,
    G_AWESOME_CODE_ellipsish = 0xf141,
    G_AWESOME_CODE_ellipsisv = 0xf142,
    G_AWESOME_CODE_empire = 0xf1d1,
    G_AWESOME_CODE_envelope = 0xf0e0,
    G_AWESOME_CODE_envelopeo = 0xf003,
    G_AWESOME_CODE_envelopeopen = 0xf2b6,
    G_AWESOME_CODE_envelopeopeno = 0xf2b7,
    G_AWESOME_CODE_envelopesquare = 0xf199,
    G_AWESOME_CODE_envira = 0xf299,
    G_AWESOME_CODE_eraser = 0xf12d,
    G_AWESOME_CODE_etsy = 0xf2d7,
    G_AWESOME_CODE_eur = 0xf153,
    G_AWESOME_CODE_euro = 0xf153,
    G_AWESOME_CODE_exchange = 0xf0ec,
    G_AWESOME_CODE_exclamation = 0xf12a,
    G_AWESOME_CODE_exclamationcircle = 0xf06a,
    G_AWESOME_CODE_exclamationtriangle = 0xf071,
    G_AWESOME_CODE_expand = 0xf065,
    G_AWESOME_CODE_expeditedssl = 0xf23e,
    G_AWESOME_CODE_externallink = 0xf08e,
    G_AWESOME_CODE_externallinksquare = 0xf14c,
    G_AWESOME_CODE_eye = 0xf06e,
    G_AWESOME_CODE_eyeslash = 0xf070,
    G_AWESOME_CODE_eyedropper = 0xf1fb,
    G_AWESOME_CODE_fa = 0xf2b4,
    G_AWESOME_CODE_facebook = 0xf09a,
    G_AWESOME_CODE_facebookf = 0xf09a,
    G_AWESOME_CODE_facebookofficial = 0xf230,
    G_AWESOME_CODE_facebooksquare = 0xf082,
    G_AWESOME_CODE_fastbackward = 0xf049,
    G_AWESOME_CODE_fastforward = 0xf050,
    G_AWESOME_CODE_fax = 0xf1ac,
    G_AWESOME_CODE_feed = 0xf09e,
    G_AWESOME_CODE_female = 0xf182,
    G_AWESOME_CODE_fighterjet = 0xf0fb,
    G_AWESOME_CODE_file = 0xf15b,
    G_AWESOME_CODE_filearchiveo = 0xf1c6,
    G_AWESOME_CODE_fileaudioo = 0xf1c7,
    G_AWESOME_CODE_filecodeo = 0xf1c9,
    G_AWESOME_CODE_fileexcelo = 0xf1c3,
    G_AWESOME_CODE_fileimageo = 0xf1c5,
    G_AWESOME_CODE_filemovieo = 0xf1c8,
    G_AWESOME_CODE_fileo = 0xf016,
    G_AWESOME_CODE_filepdfo = 0xf1c1,
    G_AWESOME_CODE_filephotoo = 0xf1c5,
    G_AWESOME_CODE_filepictureo = 0xf1c5,
    G_AWESOME_CODE_filepowerpointo = 0xf1c4,
    G_AWESOME_CODE_filesoundo = 0xf1c7,
    G_AWESOME_CODE_filetext = 0xf15c,
    G_AWESOME_CODE_filetexto = 0xf0f6,
    G_AWESOME_CODE_filevideoo = 0xf1c8,
    G_AWESOME_CODE_filewordo = 0xf1c2,
    G_AWESOME_CODE_filezipo = 0xf1c6,
    G_AWESOME_CODE_fileso = 0xf0c5,
    G_AWESOME_CODE_film = 0xf008,
    G_AWESOME_CODE_filter = 0xf0b0,
    G_AWESOME_CODE_fire = 0xf06d,
    G_AWESOME_CODE_fireextinguisher = 0xf134,
    G_AWESOME_CODE_firefox = 0xf269,
    G_AWESOME_CODE_firstorder = 0xf2b0,
    G_AWESOME_CODE_flag = 0xf024,
    G_AWESOME_CODE_flagcheckered = 0xf11e,
    G_AWESOME_CODE_flago = 0xf11d,
    G_AWESOME_CODE_flash = 0xf0e7,
    G_AWESOME_CODE_flask = 0xf0c3,
    G_AWESOME_CODE_flickr = 0xf16e,
    G_AWESOME_CODE_floppyo = 0xf0c7,
    G_AWESOME_CODE_folder = 0xf07b,
    G_AWESOME_CODE_foldero = 0xf114,
    G_AWESOME_CODE_folderopen = 0xf07c,
    G_AWESOME_CODE_folderopeno = 0xf115,
    G_AWESOME_CODE_font = 0xf031,
    G_AWESOME_CODE_fontawesome = 0xf2b4,
    G_AWESOME_CODE_fonticons = 0xf280,
    G_AWESOME_CODE_fortawesome = 0xf286,
    G_AWESOME_CODE_forumbee = 0xf211,
    G_AWESOME_CODE_forward = 0xf04e,
    G_AWESOME_CODE_foursquare = 0xf180,
    G_AWESOME_CODE_freecodecamp = 0xf2c5,
    G_AWESOME_CODE_frowno = 0xf119,
    G_AWESOME_CODE_futbolo = 0xf1e3,
    G_AWESOME_CODE_gamepad = 0xf11b,
    G_AWESOME_CODE_gavel = 0xf0e3,
    G_AWESOME_CODE_gbp = 0xf154,
    G_AWESOME_CODE_ge = 0xf1d1,
    G_AWESOME_CODE_gear = 0xf013,
    G_AWESOME_CODE_gears = 0xf085,
    G_AWESOME_CODE_genderless = 0xf22d,
    G_AWESOME_CODE_getpocket = 0xf265,
    G_AWESOME_CODE_gg = 0xf260,
    G_AWESOME_CODE_ggcircle = 0xf261,
    G_AWESOME_CODE_gift = 0xf06b,
    G_AWESOME_CODE_git = 0xf1d3,
    G_AWESOME_CODE_gitsquare = 0xf1d2,
    G_AWESOME_CODE_github = 0xf09b,
    G_AWESOME_CODE_githubalt = 0xf113,
    G_AWESOME_CODE_githubsquare = 0xf092,
    G_AWESOME_CODE_gitlab = 0xf296,
    G_AWESOME_CODE_gittip = 0xf184,
    G_AWESOME_CODE_glass = 0xf000,
    G_AWESOME_CODE_glide = 0xf2a5,
    G_AWESOME_CODE_glideg = 0xf2a6,
    G_AWESOME_CODE_globe = 0xf0ac,
    G_AWESOME_CODE_google = 0xf1a0,
    G_AWESOME_CODE_googleplus = 0xf0d5,
    G_AWESOME_CODE_googlepluscircle = 0xf2b3,
    G_AWESOME_CODE_googleplusofficial = 0xf2b3,
    G_AWESOME_CODE_googleplussquare = 0xf0d4,
    G_AWESOME_CODE_googlewallet = 0xf1ee,
    G_AWESOME_CODE_graduationcap = 0xf19d,
    G_AWESOME_CODE_gratipay = 0xf184,
    G_AWESOME_CODE_grav = 0xf2d6,
    G_AWESOME_CODE_group = 0xf0c0,
    G_AWESOME_CODE_hsquare = 0xf0fd,
    G_AWESOME_CODE_hackernews = 0xf1d4,
    G_AWESOME_CODE_handgrabo = 0xf255,
    G_AWESOME_CODE_handlizardo = 0xf258,
    G_AWESOME_CODE_handodown = 0xf0a7,
    G_AWESOME_CODE_handoleft = 0xf0a5,
    G_AWESOME_CODE_handoright = 0xf0a4,
    G_AWESOME_CODE_handoup = 0xf0a6,
    G_AWESOME_CODE_handpapero = 0xf256,
    G_AWESOME_CODE_handpeaceo = 0xf25b,
    G_AWESOME_CODE_handpointero = 0xf25a,
    G_AWESOME_CODE_handrocko = 0xf255,
    G_AWESOME_CODE_handscissorso = 0xf257,
    G_AWESOME_CODE_handspocko = 0xf259,
    G_AWESOME_CODE_handstopo = 0xf256,
    G_AWESOME_CODE_handshakeo = 0xf2b5,
    G_AWESOME_CODE_hardofhearing = 0xf2a4,
    G_AWESOME_CODE_hashtag = 0xf292,
    G_AWESOME_CODE_hddo = 0xf0a0,
    G_AWESOME_CODE_header = 0xf1dc,
    G_AWESOME_CODE_headphones = 0xf025,
    G_AWESOME_CODE_heart = 0xf004,
    G_AWESOME_CODE_hearto = 0xf08a,
    G_AWESOME_CODE_heartbeat = 0xf21e,
    G_AWESOME_CODE_history = 0xf1da,
    G_AWESOME_CODE_home = 0xf015,
    G_AWESOME_CODE_hospitalo = 0xf0f8,
    G_AWESOME_CODE_hotel = 0xf236,
    G_AWESOME_CODE_hourglass = 0xf254,
    G_AWESOME_CODE_hourglass1 = 0xf251,
    G_AWESOME_CODE_hourglass2 = 0xf252,
    G_AWESOME_CODE_hourglass3 = 0xf253,
    G_AWESOME_CODE_hourglassend = 0xf253,
    G_AWESOME_CODE_hourglasshalf = 0xf252,
    G_AWESOME_CODE_hourglasso = 0xf250,
    G_AWESOME_CODE_hourglassstart = 0xf251,
    G_AWESOME_CODE_houzz = 0xf27c,
    G_AWESOME_CODE_html5 = 0xf13b,
    G_AWESOME_CODE_icursor = 0xf246,
    G_AWESOME_CODE_idbadge = 0xf2c1,
    G_AWESOME_CODE_idcard = 0xf2c2,
    G_AWESOME_CODE_idcardo = 0xf2c3,
    G_AWESOME_CODE_ils = 0xf20b,
    G_AWESOME_CODE_image = 0xf03e,
    G_AWESOME_CODE_imdb = 0xf2d8,
    G_AWESOME_CODE_inbox = 0xf01c,
    G_AWESOME_CODE_indent = 0xf03c,
    G_AWESOME_CODE_industry = 0xf275,
    G_AWESOME_CODE_info = 0xf129,
    G_AWESOME_CODE_infocircle = 0xf05a,
    G_AWESOME_CODE_inr = 0xf156,
    G_AWESOME_CODE_instagram = 0xf16d,
    G_AWESOME_CODE_institution = 0xf19c,
    G_AWESOME_CODE_internetexplorer = 0xf26b,
    G_AWESOME_CODE_intersex = 0xf224,
    G_AWESOME_CODE_ioxhost = 0xf208,
    G_AWESOME_CODE_italic = 0xf033,
    G_AWESOME_CODE_joomla = 0xf1aa,
    G_AWESOME_CODE_jpy = 0xf157,
    G_AWESOME_CODE_jsfiddle = 0xf1cc,
    G_AWESOME_CODE_key = 0xf084,
    G_AWESOME_CODE_keyboardo = 0xf11c,
    G_AWESOME_CODE_krw = 0xf159,
    G_AWESOME_CODE_language = 0xf1ab,
    G_AWESOME_CODE_laptop = 0xf109,
    G_AWESOME_CODE_lastfm = 0xf202,
    G_AWESOME_CODE_lastfmsquare = 0xf203,
    G_AWESOME_CODE_leaf = 0xf06c,
    G_AWESOME_CODE_leanpub = 0xf212,
    G_AWESOME_CODE_legal = 0xf0e3,
    G_AWESOME_CODE_lemono = 0xf094,
    G_AWESOME_CODE_leveldown = 0xf149,
    G_AWESOME_CODE_levelup = 0xf148,
    G_AWESOME_CODE_lifebouy = 0xf1cd,
    G_AWESOME_CODE_lifebuoy = 0xf1cd,
    G_AWESOME_CODE_lifering = 0xf1cd,
    G_AWESOME_CODE_lifesaver = 0xf1cd,
    G_AWESOME_CODE_lightbulbo = 0xf0eb,
    G_AWESOME_CODE_linechart = 0xf201,
    G_AWESOME_CODE_link = 0xf0c1,
    G_AWESOME_CODE_linkedin = 0xf0e1,
    G_AWESOME_CODE_linkedinsquare = 0xf08c,
    G_AWESOME_CODE_linode = 0xf2b8,
    G_AWESOME_CODE_fa_linux = 0xf17c,
    G_AWESOME_CODE_list = 0xf03a,
    G_AWESOME_CODE_listalt = 0xf022,
    G_AWESOME_CODE_listol = 0xf0cb,
    G_AWESOME_CODE_listul = 0xf0ca,
    G_AWESOME_CODE_locationarrow = 0xf124,
    G_AWESOME_CODE_lock = 0xf023,
    G_AWESOME_CODE_longarrowdown = 0xf175,
    G_AWESOME_CODE_longarrowleft = 0xf177,
    G_AWESOME_CODE_longarrowright = 0xf178,
    G_AWESOME_CODE_longarrowup = 0xf176,
    G_AWESOME_CODE_lowvision = 0xf2a8,
    G_AWESOME_CODE_magic = 0xf0d0,
    G_AWESOME_CODE_magnet = 0xf076,
    G_AWESOME_CODE_mailforward = 0xf064,
    G_AWESOME_CODE_mailreply = 0xf112,
    G_AWESOME_CODE_mailreplyall = 0xf122,
    G_AWESOME_CODE_male = 0xf183,
    G_AWESOME_CODE_map = 0xf279,
    G_AWESOME_CODE_mapmarker = 0xf041,
    G_AWESOME_CODE_mapo = 0xf278,
    G_AWESOME_CODE_mappin = 0xf276,
    G_AWESOME_CODE_mapsigns = 0xf277,
    G_AWESOME_CODE_mars = 0xf222,
    G_AWESOME_CODE_marsdouble = 0xf227,
    G_AWESOME_CODE_marsstroke = 0xf229,
    G_AWESOME_CODE_marsstrokeh = 0xf22b,
    G_AWESOME_CODE_marsstrokev = 0xf22a,
    G_AWESOME_CODE_maxcdn = 0xf136,
    G_AWESOME_CODE_meanpath = 0xf20c,
    G_AWESOME_CODE_medium = 0xf23a,
    G_AWESOME_CODE_medkit = 0xf0fa,
    G_AWESOME_CODE_meetup = 0xf2e0,
    G_AWESOME_CODE_meho = 0xf11a,
    G_AWESOME_CODE_mercury = 0xf223,
    G_AWESOME_CODE_microchip = 0xf2db,
    G_AWESOME_CODE_microphone = 0xf130,
    G_AWESOME_CODE_microphoneslash = 0xf131,
    G_AWESOME_CODE_minus = 0xf068,
    G_AWESOME_CODE_minuscircle = 0xf056,
    G_AWESOME_CODE_minussquare = 0xf146,
    G_AWESOME_CODE_minussquareo = 0xf147,
    G_AWESOME_CODE_mixcloud = 0xf289,
    G_AWESOME_CODE_mobile = 0xf10b,
    G_AWESOME_CODE_mobilephone = 0xf10b,
    G_AWESOME_CODE_modx = 0xf285,
    G_AWESOME_CODE_money = 0xf0d6,
    G_AWESOME_CODE_moono = 0xf186,
    G_AWESOME_CODE_mortarboard = 0xf19d,
    G_AWESOME_CODE_motorcycle = 0xf21c,
    G_AWESOME_CODE_mousepointer = 0xf245,
    G_AWESOME_CODE_music = 0xf001,
    G_AWESOME_CODE_navicon = 0xf0c9,
    G_AWESOME_CODE_neuter = 0xf22c,
    G_AWESOME_CODE_newspapero = 0xf1ea,
    G_AWESOME_CODE_objectgroup = 0xf247,
    G_AWESOME_CODE_objectungroup = 0xf248,
    G_AWESOME_CODE_odnoklassniki = 0xf263,
    G_AWESOME_CODE_odnoklassnikisquare = 0xf264,
    G_AWESOME_CODE_opencart = 0xf23d,
    G_AWESOME_CODE_openid = 0xf19b,
    G_AWESOME_CODE_opera = 0xf26a,
    G_AWESOME_CODE_optinmonster = 0xf23c,
    G_AWESOME_CODE_outdent = 0xf03b,
    G_AWESOME_CODE_pagelines = 0xf18c,
    G_AWESOME_CODE_paintbrush = 0xf1fc,
    G_AWESOME_CODE_paperplane = 0xf1d8,
    G_AWESOME_CODE_paperplaneo = 0xf1d9,
    G_AWESOME_CODE_paperclip = 0xf0c6,
    G_AWESOME_CODE_paragraph = 0xf1dd,
    G_AWESOME_CODE_paste = 0xf0ea,
    G_AWESOME_CODE_pause = 0xf04c,
    G_AWESOME_CODE_pausecircle = 0xf28b,
    G_AWESOME_CODE_pausecircleo = 0xf28c,
    G_AWESOME_CODE_paw = 0xf1b0,
    G_AWESOME_CODE_paypal = 0xf1ed,
    G_AWESOME_CODE_pencil = 0xf040,
    G_AWESOME_CODE_pencilsquare = 0xf14b,
    G_AWESOME_CODE_pencilsquareo = 0xf044,
    G_AWESOME_CODE_percent = 0xf295,
    G_AWESOME_CODE_phone = 0xf095,
    G_AWESOME_CODE_phonesquare = 0xf098,
    G_AWESOME_CODE_photo = 0xf03e,
    G_AWESOME_CODE_pictureo = 0xf03e,
    G_AWESOME_CODE_piechart = 0xf200,
    G_AWESOME_CODE_piedpiper = 0xf2ae,
    G_AWESOME_CODE_piedpiperalt = 0xf1a8,
    G_AWESOME_CODE_piedpiperpp = 0xf1a7,
    G_AWESOME_CODE_pinterest = 0xf0d2,
    G_AWESOME_CODE_pinterestp = 0xf231,
    G_AWESOME_CODE_pinterestsquare = 0xf0d3,
    G_AWESOME_CODE_plane = 0xf072,
    G_AWESOME_CODE_play = 0xf04b,
    G_AWESOME_CODE_playcircle = 0xf144,
    G_AWESOME_CODE_playcircleo = 0xf01d,
    G_AWESOME_CODE_plug = 0xf1e6,
    G_AWESOME_CODE_plus = 0xf067,
    G_AWESOME_CODE_pluscircle = 0xf055,
    G_AWESOME_CODE_plussquare = 0xf0fe,
    G_AWESOME_CODE_plussquareo = 0xf196,
    G_AWESOME_CODE_podcast = 0xf2ce,
    G_AWESOME_CODE_poweroff = 0xf011,
    G_AWESOME_CODE_print = 0xf02f,
    G_AWESOME_CODE_producthunt = 0xf288,
    G_AWESOME_CODE_puzzlepiece = 0xf12e,
    G_AWESOME_CODE_qq = 0xf1d6,
    G_AWESOME_CODE_qrcode = 0xf029,
    G_AWESOME_CODE_question = 0xf128,
    G_AWESOME_CODE_questioncircle = 0xf059,
    G_AWESOME_CODE_questioncircleo = 0xf29c,
    G_AWESOME_CODE_quora = 0xf2c4,
    G_AWESOME_CODE_quoteleft = 0xf10d,
    G_AWESOME_CODE_quoteright = 0xf10e,
    G_AWESOME_CODE_ra = 0xf1d0,
    G_AWESOME_CODE_random = 0xf074,
    G_AWESOME_CODE_ravelry = 0xf2d9,
    G_AWESOME_CODE_rebel = 0xf1d0,
    G_AWESOME_CODE_recycle = 0xf1b8,
    G_AWESOME_CODE_reddit = 0xf1a1,
    G_AWESOME_CODE_redditalien = 0xf281,
    G_AWESOME_CODE_redditsquare = 0xf1a2,
    G_AWESOME_CODE_refresh = 0xf021,
    G_AWESOME_CODE_registered = 0xf25d,
    G_AWESOME_CODE_remove = 0xf00d,
    G_AWESOME_CODE_renren = 0xf18b,
    G_AWESOME_CODE_reorder = 0xf0c9,
    G_AWESOME_CODE_repeat = 0xf01e,
    G_AWESOME_CODE_reply = 0xf112,
    G_AWESOME_CODE_replyall = 0xf122,
    G_AWESOME_CODE_resistance = 0xf1d0,
    G_AWESOME_CODE_retweet = 0xf079,
    G_AWESOME_CODE_rmb = 0xf157,
    G_AWESOME_CODE_road = 0xf018,
    G_AWESOME_CODE_rocket = 0xf135,
    G_AWESOME_CODE_rotateleft = 0xf0e2,
    G_AWESOME_CODE_rotateright = 0xf01e,
    G_AWESOME_CODE_rouble = 0xf158,
    G_AWESOME_CODE_rss = 0xf09e,
    G_AWESOME_CODE_rsssquare = 0xf143,
    G_AWESOME_CODE_rub = 0xf158,
    G_AWESOME_CODE_ruble = 0xf158,
    G_AWESOME_CODE_rupee = 0xf156,
    G_AWESOME_CODE_s15 = 0xf2cd,
    G_AWESOME_CODE_safari = 0xf267,
    G_AWESOME_CODE_save = 0xf0c7,
    G_AWESOME_CODE_scissors = 0xf0c4,
    G_AWESOME_CODE_scribd = 0xf28a,
    G_AWESOME_CODE_search = 0xf002,
    G_AWESOME_CODE_searchminus = 0xf010,
    G_AWESOME_CODE_searchplus = 0xf00e,
    G_AWESOME_CODE_sellsy = 0xf213,
    G_AWESOME_CODE_send = 0xf1d8,
    G_AWESOME_CODE_sendo = 0xf1d9,
    G_AWESOME_CODE_server = 0xf233,
    G_AWESOME_CODE_share = 0xf064,
    G_AWESOME_CODE_sharealt = 0xf1e0,
    G_AWESOME_CODE_sharealtsquare = 0xf1e1,
    G_AWESOME_CODE_sharesquare = 0xf14d,
    G_AWESOME_CODE_sharesquareo = 0xf045,
    G_AWESOME_CODE_shekel = 0xf20b,
    G_AWESOME_CODE_sheqel = 0xf20b,
    G_AWESOME_CODE_shield = 0xf132,
    G_AWESOME_CODE_ship = 0xf21a,
    G_AWESOME_CODE_shirtsinbulk = 0xf214,
    G_AWESOME_CODE_shoppingbag = 0xf290,
    G_AWESOME_CODE_shoppingbasket = 0xf291,
    G_AWESOME_CODE_shoppingcart = 0xf07a,
    G_AWESOME_CODE_shower = 0xf2cc,
    G_AWESOME_CODE_signin = 0xf090,
    G_AWESOME_CODE_signlanguage = 0xf2a7,
    G_AWESOME_CODE_signout = 0xf08b,
    G_AWESOME_CODE_signal = 0xf012,
    G_AWESOME_CODE_signing = 0xf2a7,
    G_AWESOME_CODE_simplybuilt = 0xf215,
    G_AWESOME_CODE_sitemap = 0xf0e8,
    G_AWESOME_CODE_skyatlas = 0xf216,
    G_AWESOME_CODE_skype = 0xf17e,
    G_AWESOME_CODE_slack = 0xf198,
    G_AWESOME_CODE_sliders = 0xf1de,
    G_AWESOME_CODE_slideshare = 0xf1e7,
    G_AWESOME_CODE_smileo = 0xf118,
    G_AWESOME_CODE_snapchat = 0xf2ab,
    G_AWESOME_CODE_snapchatghost = 0xf2ac,
    G_AWESOME_CODE_snapchatsquare = 0xf2ad,
    G_AWESOME_CODE_snowflakeo = 0xf2dc,
    G_AWESOME_CODE_soccerballo = 0xf1e3,
    G_AWESOME_CODE_sort = 0xf0dc,
    G_AWESOME_CODE_sortalphaasc = 0xf15d,
    G_AWESOME_CODE_sortalphadesc = 0xf15e,
    G_AWESOME_CODE_sortamountasc = 0xf160,
    G_AWESOME_CODE_sortamountdesc = 0xf161,
    G_AWESOME_CODE_sortasc = 0xf0de,
    G_AWESOME_CODE_sortdesc = 0xf0dd,
    G_AWESOME_CODE_sortdown = 0xf0dd,
    G_AWESOME_CODE_sortnumericasc = 0xf162,
    G_AWESOME_CODE_sortnumericdesc = 0xf163,
    G_AWESOME_CODE_sortup = 0xf0de,
    G_AWESOME_CODE_soundcloud = 0xf1be,
    G_AWESOME_CODE_spaceshuttle = 0xf197,
    G_AWESOME_CODE_spinner = 0xf110,
    G_AWESOME_CODE_spoon = 0xf1b1,
    G_AWESOME_CODE_spotify = 0xf1bc,
    G_AWESOME_CODE_square = 0xf0c8,
    G_AWESOME_CODE_squareo = 0xf096,
    G_AWESOME_CODE_stackexchange = 0xf18d,
    G_AWESOME_CODE_stackoverflow = 0xf16c,
    G_AWESOME_CODE_star = 0xf005,
    G_AWESOME_CODE_starhalf = 0xf089,
    G_AWESOME_CODE_starhalfempty = 0xf123,
    G_AWESOME_CODE_starhalffull = 0xf123,
    G_AWESOME_CODE_starhalfo = 0xf123,
    G_AWESOME_CODE_staro = 0xf006,
    G_AWESOME_CODE_steam = 0xf1b6,
    G_AWESOME_CODE_steamsquare = 0xf1b7,
    G_AWESOME_CODE_stepbackward = 0xf048,
    G_AWESOME_CODE_stepforward = 0xf051,
    G_AWESOME_CODE_stethoscope = 0xf0f1,
    G_AWESOME_CODE_stickynote = 0xf249,
    G_AWESOME_CODE_stickynoteo = 0xf24a,
    G_AWESOME_CODE_stop = 0xf04d,
    G_AWESOME_CODE_stopcircle = 0xf28d,
    G_AWESOME_CODE_stopcircleo = 0xf28e,
    G_AWESOME_CODE_streetview = 0xf21d,
    G_AWESOME_CODE_strikethrough = 0xf0cc,
    G_AWESOME_CODE_stumbleupon = 0xf1a4,
    G_AWESOME_CODE_stumbleuponcircle = 0xf1a3,
    G_AWESOME_CODE_subscript = 0xf12c,
    G_AWESOME_CODE_subway = 0xf239,
    G_AWESOME_CODE_suitcase = 0xf0f2,
    G_AWESOME_CODE_suno = 0xf185,
    G_AWESOME_CODE_superpowers = 0xf2dd,
    G_AWESOME_CODE_superscript = 0xf12b,
    G_AWESOME_CODE_support = 0xf1cd,
    G_AWESOME_CODE_table = 0xf0ce,
    G_AWESOME_CODE_tablet = 0xf10a,
    G_AWESOME_CODE_tachometer = 0xf0e4,
    G_AWESOME_CODE_tag = 0xf02b,
    G_AWESOME_CODE_tags = 0xf02c,
    G_AWESOME_CODE_tasks = 0xf0ae,
    G_AWESOME_CODE_taxi = 0xf1ba,
    G_AWESOME_CODE_telegram = 0xf2c6,
    G_AWESOME_CODE_television = 0xf26c,
    G_AWESOME_CODE_tencentweibo = 0xf1d5,
    G_AWESOME_CODE_terminal = 0xf120,
    G_AWESOME_CODE_textheight = 0xf034,
    G_AWESOME_CODE_textwidth = 0xf035,
    G_AWESOME_CODE_th = 0xf00a,
    G_AWESOME_CODE_thlarge = 0xf009,
    G_AWESOME_CODE_thlist = 0xf00b,
    G_AWESOME_CODE_themeisle = 0xf2b2,
    G_AWESOME_CODE_thermometer = 0xf2c7,
    G_AWESOME_CODE_thermometer0 = 0xf2cb,
    G_AWESOME_CODE_thermometer1 = 0xf2ca,
    G_AWESOME_CODE_thermometer2 = 0xf2c9,
    G_AWESOME_CODE_thermometer3 = 0xf2c8,
    G_AWESOME_CODE_thermometer4 = 0xf2c7,
    G_AWESOME_CODE_thermometerempty = 0xf2cb,
    G_AWESOME_CODE_thermometerfull = 0xf2c7,
    G_AWESOME_CODE_thermometerhalf = 0xf2c9,
    G_AWESOME_CODE_thermometerquarter = 0xf2ca,
    G_AWESOME_CODE_thermometerthreequarters = 0xf2c8,
    G_AWESOME_CODE_thumbtack = 0xf08d,
    G_AWESOME_CODE_thumbsdown = 0xf165,
    G_AWESOME_CODE_thumbsodown = 0xf088,
    G_AWESOME_CODE_thumbsoup = 0xf087,
    G_AWESOME_CODE_thumbsup = 0xf164,
    G_AWESOME_CODE_ticket = 0xf145,
    G_AWESOME_CODE_times = 0xf00d,
    G_AWESOME_CODE_timescircle = 0xf057,
    G_AWESOME_CODE_timescircleo = 0xf05c,
    G_AWESOME_CODE_timesrectangle = 0xf2d3,
    G_AWESOME_CODE_timesrectangleo = 0xf2d4,
    G_AWESOME_CODE_tint = 0xf043,
    G_AWESOME_CODE_toggledown = 0xf150,
    G_AWESOME_CODE_toggleleft = 0xf191,
    G_AWESOME_CODE_toggleoff = 0xf204,
    G_AWESOME_CODE_toggleon = 0xf205,
    G_AWESOME_CODE_toggleright = 0xf152,
    G_AWESOME_CODE_toggleup = 0xf151,
    G_AWESOME_CODE_trademark = 0xf25c,
    G_AWESOME_CODE_train = 0xf238,
    G_AWESOME_CODE_transgender = 0xf224,
    G_AWESOME_CODE_transgenderalt = 0xf225,
    G_AWESOME_CODE_trash = 0xf1f8,
    G_AWESOME_CODE_trasho = 0xf014,
    G_AWESOME_CODE_tree = 0xf1bb,
    G_AWESOME_CODE_trello = 0xf181,
    G_AWESOME_CODE_tripadvisor = 0xf262,
    G_AWESOME_CODE_trophy = 0xf091,
    G_AWESOME_CODE_truck = 0xf0d1,
    G_AWESOME_CODE_fa_try = 0xf195,
    G_AWESOME_CODE_tty = 0xf1e4,
    G_AWESOME_CODE_tumblr = 0xf173,
    G_AWESOME_CODE_tumblrsquare = 0xf174,
    G_AWESOME_CODE_turkishlira = 0xf195,
    G_AWESOME_CODE_tv = 0xf26c,
    G_AWESOME_CODE_twitch = 0xf1e8,
    G_AWESOME_CODE_twitter = 0xf099,
    G_AWESOME_CODE_twittersquare = 0xf081,
    G_AWESOME_CODE_umbrella = 0xf0e9,
    G_AWESOME_CODE_underline = 0xf0cd,
    G_AWESOME_CODE_undo = 0xf0e2,
    G_AWESOME_CODE_universalaccess = 0xf29a,
    G_AWESOME_CODE_university = 0xf19c,
    G_AWESOME_CODE_unlink = 0xf127,
    G_AWESOME_CODE_unlock = 0xf09c,
    G_AWESOME_CODE_unlockalt = 0xf13e,
    G_AWESOME_CODE_unsorted = 0xf0dc,
    G_AWESOME_CODE_upload = 0xf093,
    G_AWESOME_CODE_usb = 0xf287,
    G_AWESOME_CODE_usd = 0xf155,
    G_AWESOME_CODE_user = 0xf007,
    G_AWESOME_CODE_usercircle = 0xf2bd,
    G_AWESOME_CODE_usercircleo = 0xf2be,
    G_AWESOME_CODE_usermd = 0xf0f0,
    G_AWESOME_CODE_usero = 0xf2c0,
    G_AWESOME_CODE_userplus = 0xf234,
    G_AWESOME_CODE_usersecret = 0xf21b,
    G_AWESOME_CODE_usertimes = 0xf235,
    G_AWESOME_CODE_users = 0xf0c0,
    G_AWESOME_CODE_vcard = 0xf2bb,
    G_AWESOME_CODE_vcardo = 0xf2bc,
    G_AWESOME_CODE_venus = 0xf221,
    G_AWESOME_CODE_venusdouble = 0xf226,
    G_AWESOME_CODE_venusmars = 0xf228,
    G_AWESOME_CODE_viacoin = 0xf237,
    G_AWESOME_CODE_viadeo = 0xf2a9,
    G_AWESOME_CODE_viadeosquare = 0xf2aa,
    G_AWESOME_CODE_videocamera = 0xf03d,
    G_AWESOME_CODE_vimeo = 0xf27d,
    G_AWESOME_CODE_vimeosquare = 0xf194,
    G_AWESOME_CODE_vine = 0xf1ca,
    G_AWESOME_CODE_vk = 0xf189,
    G_AWESOME_CODE_volumecontrolphone = 0xf2a0,
    G_AWESOME_CODE_volumedown = 0xf027,
    G_AWESOME_CODE_volumeoff = 0xf026,
    G_AWESOME_CODE_volumeup = 0xf028,
    G_AWESOME_CODE_warning = 0xf071,
    G_AWESOME_CODE_wechat = 0xf1d7,
    G_AWESOME_CODE_weibo = 0xf18a,
    G_AWESOME_CODE_weixin = 0xf1d7,
    G_AWESOME_CODE_whatsapp = 0xf232,
    G_AWESOME_CODE_wheelchair = 0xf193,
    G_AWESOME_CODE_wheelchairalt = 0xf29b,
    G_AWESOME_CODE_wifi = 0xf1eb,
    G_AWESOME_CODE_wikipediaw = 0xf266,
    G_AWESOME_CODE_windowclose = 0xf2d3,
    G_AWESOME_CODE_windowcloseo = 0xf2d4,
    G_AWESOME_CODE_windowmaximize = 0xf2d0,
    G_AWESOME_CODE_windowminimize = 0xf2d1,
    G_AWESOME_CODE_windowrestore = 0xf2d2,
    G_AWESOME_CODE_windows = 0xf17a,
    G_AWESOME_CODE_won = 0xf159,
    G_AWESOME_CODE_wordpress = 0xf19a,
    G_AWESOME_CODE_wpbeginner = 0xf297,
    G_AWESOME_CODE_wpexplorer = 0xf2de,
    G_AWESOME_CODE_wpforms = 0xf298,
    G_AWESOME_CODE_wrench = 0xf0ad,
    G_AWESOME_CODE_xing = 0xf168,
    G_AWESOME_CODE_xingsquare = 0xf169,
    G_AWESOME_CODE_ycombinator = 0xf23b,
    G_AWESOME_CODE_ycombinatorsquare = 0xf1d4,
    G_AWESOME_CODE_yahoo = 0xf19e,
    G_AWESOME_CODE_yc = 0xf23b,
    G_AWESOME_CODE_ycsquare = 0xf1d4,
    G_AWESOME_CODE_yelp = 0xf1e9,
    G_AWESOME_CODE_yen = 0xf157,
    G_AWESOME_CODE_yoast = 0xf2b1,
    G_AWESOME_CODE_youtube = 0xf167,
    G_AWESOME_CODE_youtubeplay = 0xf16a,
    G_AWESOME_CODE_youtubesquare = 0xf166
} GAwesomeCode;

struct _GAwesomeNameIcon {
    const gchar *name;
    GAwesomeCode code;
};



static const struct _GAwesomeNameIcon gaNameIconArray[] = {
    { "fa_500px", G_AWESOME_CODE_fa_500px },
    { "addressbook", G_AWESOME_CODE_addressbook },
    { "addressbooko", G_AWESOME_CODE_addressbooko },
    { "addresscard", G_AWESOME_CODE_addresscard },
    { "addresscardo", G_AWESOME_CODE_addresscardo },
    { "adjust", G_AWESOME_CODE_adjust },
    { "adn", G_AWESOME_CODE_adn },
    { "aligncenter", G_AWESOME_CODE_aligncenter },
    { "alignjustify", G_AWESOME_CODE_alignjustify },
    { "alignleft", G_AWESOME_CODE_alignleft },
    { "alignright", G_AWESOME_CODE_alignright },
    { "amazon", G_AWESOME_CODE_amazon },
    { "ambulance", G_AWESOME_CODE_ambulance },
    { "americansignlanguageinterpreting", G_AWESOME_CODE_americansignlanguageinterpreting },
    { "anchor", G_AWESOME_CODE_anchor },
    { "android", G_AWESOME_CODE_android },
    { "angellist", G_AWESOME_CODE_angellist },
    { "angledoubledown", G_AWESOME_CODE_angledoubledown },
    { "angledoubleleft", G_AWESOME_CODE_angledoubleleft },
    { "angledoubleright", G_AWESOME_CODE_angledoubleright },
    { "angledoubleup", G_AWESOME_CODE_angledoubleup },
    { "angledown", G_AWESOME_CODE_angledown },
    { "angleleft", G_AWESOME_CODE_angleleft },
    { "angleright", G_AWESOME_CODE_angleright },
    { "angleup", G_AWESOME_CODE_angleup },
    { "apple", G_AWESOME_CODE_apple },
    { "archive", G_AWESOME_CODE_archive },
    { "areachart", G_AWESOME_CODE_areachart },
    { "arrowcircledown", G_AWESOME_CODE_arrowcircledown },
    { "arrowcircleleft", G_AWESOME_CODE_arrowcircleleft },
    { "arrowcircleodown", G_AWESOME_CODE_arrowcircleodown },
    { "arrowcircleoleft", G_AWESOME_CODE_arrowcircleoleft },
    { "arrowcircleoright", G_AWESOME_CODE_arrowcircleoright },
    { "arrowcircleoup", G_AWESOME_CODE_arrowcircleoup },
    { "arrowcircleright", G_AWESOME_CODE_arrowcircleright },
    { "arrowcircleup", G_AWESOME_CODE_arrowcircleup },
    { "arrowdown", G_AWESOME_CODE_arrowdown },
    { "arrowleft", G_AWESOME_CODE_arrowleft },
    { "arrowright", G_AWESOME_CODE_arrowright },
    { "arrowup", G_AWESOME_CODE_arrowup },
    { "arrows", G_AWESOME_CODE_arrows },
    { "arrowsalt", G_AWESOME_CODE_arrowsalt },
    { "arrowsh", G_AWESOME_CODE_arrowsh },
    { "arrowsv", G_AWESOME_CODE_arrowsv },
    { "aslinterpreting", G_AWESOME_CODE_aslinterpreting },
    { "assistivelisteningsystems", G_AWESOME_CODE_assistivelisteningsystems },
    { "asterisk", G_AWESOME_CODE_asterisk },
    { "at", G_AWESOME_CODE_at },
    { "audiodescription", G_AWESOME_CODE_audiodescription },
    { "automobile", G_AWESOME_CODE_automobile },
    { "backward", G_AWESOME_CODE_backward },
    { "balancescale", G_AWESOME_CODE_balancescale },
    { "ban", G_AWESOME_CODE_ban },
    { "bandcamp", G_AWESOME_CODE_bandcamp },
    { "bank", G_AWESOME_CODE_bank },
    { "barchart", G_AWESOME_CODE_barchart },
    { "barcharto", G_AWESOME_CODE_barcharto },
    { "barcode", G_AWESOME_CODE_barcode },
    { "bars", G_AWESOME_CODE_bars },
    { "bath", G_AWESOME_CODE_bath },
    { "bathtub", G_AWESOME_CODE_bathtub },
    { "battery", G_AWESOME_CODE_battery },
    { "battery0", G_AWESOME_CODE_battery0 },
    { "battery1", G_AWESOME_CODE_battery1 },
    { "battery2", G_AWESOME_CODE_battery2 },
    { "battery3", G_AWESOME_CODE_battery3 },
    { "battery4", G_AWESOME_CODE_battery4 },
    { "batteryempty", G_AWESOME_CODE_batteryempty },
    { "batteryfull", G_AWESOME_CODE_batteryfull },
    { "batteryhalf", G_AWESOME_CODE_batteryhalf },
    { "batteryquarter", G_AWESOME_CODE_batteryquarter },
    { "batterythreequarters", G_AWESOME_CODE_batterythreequarters },
    { "bed", G_AWESOME_CODE_bed },
    { "beer", G_AWESOME_CODE_beer },
    { "behance", G_AWESOME_CODE_behance },
    { "behancesquare", G_AWESOME_CODE_behancesquare },
    { "bell", G_AWESOME_CODE_bell },
    { "bello", G_AWESOME_CODE_bello },
    { "bellslash", G_AWESOME_CODE_bellslash },
    { "bellslasho", G_AWESOME_CODE_bellslasho },
    { "bicycle", G_AWESOME_CODE_bicycle },
    { "binoculars", G_AWESOME_CODE_binoculars },
    { "birthdaycake", G_AWESOME_CODE_birthdaycake },
    { "bitbucket", G_AWESOME_CODE_bitbucket },
    { "bitbucketsquare", G_AWESOME_CODE_bitbucketsquare },
    { "bitcoin", G_AWESOME_CODE_bitcoin },
    { "blacktie", G_AWESOME_CODE_blacktie },
    { "blind", G_AWESOME_CODE_blind },
    { "bluetooth", G_AWESOME_CODE_bluetooth },
    { "bluetoothb", G_AWESOME_CODE_bluetoothb },
    { "bold", G_AWESOME_CODE_bold },
    { "bolt", G_AWESOME_CODE_bolt },
    { "bomb", G_AWESOME_CODE_bomb },
    { "book", G_AWESOME_CODE_book },
    { "bookmark", G_AWESOME_CODE_bookmark },
    { "bookmarko", G_AWESOME_CODE_bookmarko },
    { "braille", G_AWESOME_CODE_braille },
    { "briefcase", G_AWESOME_CODE_briefcase },
    { "btc", G_AWESOME_CODE_btc },
    { "bug", G_AWESOME_CODE_bug },
    { "building", G_AWESOME_CODE_building },
    { "buildingo", G_AWESOME_CODE_buildingo },
    { "bullhorn", G_AWESOME_CODE_bullhorn },
    { "bullseye", G_AWESOME_CODE_bullseye },
    { "bus", G_AWESOME_CODE_bus },
    { "buysellads", G_AWESOME_CODE_buysellads },
    { "cab", G_AWESOME_CODE_cab },
    { "calculator", G_AWESOME_CODE_calculator },
    { "calendar", G_AWESOME_CODE_calendar },
    { "calendarchecko", G_AWESOME_CODE_calendarchecko },
    { "calendarminuso", G_AWESOME_CODE_calendarminuso },
    { "calendaro", G_AWESOME_CODE_calendaro },
    { "calendarpluso", G_AWESOME_CODE_calendarpluso },
    { "calendartimeso", G_AWESOME_CODE_calendartimeso },
    { "camera", G_AWESOME_CODE_camera },
    { "cameraretro", G_AWESOME_CODE_cameraretro },
    { "car", G_AWESOME_CODE_car },
    { "caretdown", G_AWESOME_CODE_caretdown },
    { "caretleft", G_AWESOME_CODE_caretleft },
    { "caretright", G_AWESOME_CODE_caretright },
    { "caretsquareodown", G_AWESOME_CODE_caretsquareodown },
    { "caretsquareoleft", G_AWESOME_CODE_caretsquareoleft },
    { "caretsquareoright", G_AWESOME_CODE_caretsquareoright },
    { "caretsquareoup", G_AWESOME_CODE_caretsquareoup },
    { "caretup", G_AWESOME_CODE_caretup },
    { "cartarrowdown", G_AWESOME_CODE_cartarrowdown },
    { "cartplus", G_AWESOME_CODE_cartplus },
    { "cc", G_AWESOME_CODE_cc },
    { "ccamex", G_AWESOME_CODE_ccamex },
    { "ccdinersclub", G_AWESOME_CODE_ccdinersclub },
    { "ccdiscover", G_AWESOME_CODE_ccdiscover },
    { "ccjcb", G_AWESOME_CODE_ccjcb },
    { "ccmastercard", G_AWESOME_CODE_ccmastercard },
    { "ccpaypal", G_AWESOME_CODE_ccpaypal },
    { "ccstripe", G_AWESOME_CODE_ccstripe },
    { "ccvisa", G_AWESOME_CODE_ccvisa },
    { "certificate", G_AWESOME_CODE_certificate },
    { "chain", G_AWESOME_CODE_chain },
    { "chainbroken", G_AWESOME_CODE_chainbroken },
    { "check", G_AWESOME_CODE_check },
    { "checkcircle", G_AWESOME_CODE_checkcircle },
    { "checkcircleo", G_AWESOME_CODE_checkcircleo },
    { "checksquare", G_AWESOME_CODE_checksquare },
    { "checksquareo", G_AWESOME_CODE_checksquareo },
    { "chevroncircledown", G_AWESOME_CODE_chevroncircledown },
    { "chevroncircleleft", G_AWESOME_CODE_chevroncircleleft },
    { "chevroncircleright", G_AWESOME_CODE_chevroncircleright },
    { "chevroncircleup", G_AWESOME_CODE_chevroncircleup },
    { "chevrondown", G_AWESOME_CODE_chevrondown },
    { "chevronleft", G_AWESOME_CODE_chevronleft },
    { "chevronright", G_AWESOME_CODE_chevronright },
    { "chevronup", G_AWESOME_CODE_chevronup },
    { "child", G_AWESOME_CODE_child },
    { "chrome", G_AWESOME_CODE_chrome },
    { "circle", G_AWESOME_CODE_circle },
    { "circleo", G_AWESOME_CODE_circleo },
    { "circleonotch", G_AWESOME_CODE_circleonotch },
    { "circlethin", G_AWESOME_CODE_circlethin },
    { "clipboard", G_AWESOME_CODE_clipboard },
    { "clocko", G_AWESOME_CODE_clocko },
    { "clone", G_AWESOME_CODE_clone },
    { "close", G_AWESOME_CODE_close },
    { "cloud", G_AWESOME_CODE_cloud },
    { "clouddownload", G_AWESOME_CODE_clouddownload },
    { "cloudupload", G_AWESOME_CODE_cloudupload },
    { "cny", G_AWESOME_CODE_cny },
    { "code", G_AWESOME_CODE_code },
    { "codefork", G_AWESOME_CODE_codefork },
    { "codepen", G_AWESOME_CODE_codepen },
    { "codiepie", G_AWESOME_CODE_codiepie },
    { "coffee", G_AWESOME_CODE_coffee },
    { "cog", G_AWESOME_CODE_cog },
    { "cogs", G_AWESOME_CODE_cogs },
    { "columns", G_AWESOME_CODE_columns },
    { "comment", G_AWESOME_CODE_comment },
    { "commento", G_AWESOME_CODE_commento },
    { "commenting", G_AWESOME_CODE_commenting },
    { "commentingo", G_AWESOME_CODE_commentingo },
    { "comments", G_AWESOME_CODE_comments },
    { "commentso", G_AWESOME_CODE_commentso },
    { "compass", G_AWESOME_CODE_compass },
    { "compress", G_AWESOME_CODE_compress },
    { "connectdevelop", G_AWESOME_CODE_connectdevelop },
    { "contao", G_AWESOME_CODE_contao },
    { "copy", G_AWESOME_CODE_copy },
    { "copyright", G_AWESOME_CODE_copyright },
    { "creativecommons", G_AWESOME_CODE_creativecommons },
    { "creditcard", G_AWESOME_CODE_creditcard },
    { "creditcardalt", G_AWESOME_CODE_creditcardalt },
    { "crop", G_AWESOME_CODE_crop },
    { "crosshairs", G_AWESOME_CODE_crosshairs },
    { "css3", G_AWESOME_CODE_css3 },
    { "cube", G_AWESOME_CODE_cube },
    { "cubes", G_AWESOME_CODE_cubes },
    { "cut", G_AWESOME_CODE_cut },
    { "cutlery", G_AWESOME_CODE_cutlery },
    { "dashboard", G_AWESOME_CODE_dashboard },
    { "dashcube", G_AWESOME_CODE_dashcube },
    { "database", G_AWESOME_CODE_database },
    { "deaf", G_AWESOME_CODE_deaf },
    { "deafness", G_AWESOME_CODE_deafness },
    { "dedent", G_AWESOME_CODE_dedent },
    { "delicious", G_AWESOME_CODE_delicious },
    { "desktop", G_AWESOME_CODE_desktop },
    { "deviantart", G_AWESOME_CODE_deviantart },
    { "diamond", G_AWESOME_CODE_diamond },
    { "digg", G_AWESOME_CODE_digg },
    { "dollar", G_AWESOME_CODE_dollar },
    { "dotcircleo", G_AWESOME_CODE_dotcircleo },
    { "download", G_AWESOME_CODE_download },
    { "dribbble", G_AWESOME_CODE_dribbble },
    { "driverslicense", G_AWESOME_CODE_driverslicense },
    { "driverslicenseo", G_AWESOME_CODE_driverslicenseo },
    { "dropbox", G_AWESOME_CODE_dropbox },
    { "drupal", G_AWESOME_CODE_drupal },
    { "edge", G_AWESOME_CODE_edge },
    { "edit", G_AWESOME_CODE_edit },
    { "eercast", G_AWESOME_CODE_eercast },
    { "eject", G_AWESOME_CODE_eject },
    { "ellipsish", G_AWESOME_CODE_ellipsish },
    { "ellipsisv", G_AWESOME_CODE_ellipsisv },
    { "empire", G_AWESOME_CODE_empire },
    { "envelope", G_AWESOME_CODE_envelope },
    { "envelopeo", G_AWESOME_CODE_envelopeo },
    { "envelopeopen", G_AWESOME_CODE_envelopeopen },
    { "envelopeopeno", G_AWESOME_CODE_envelopeopeno },
    { "envelopesquare", G_AWESOME_CODE_envelopesquare },
    { "envira", G_AWESOME_CODE_envira },
    { "eraser", G_AWESOME_CODE_eraser },
    { "etsy", G_AWESOME_CODE_etsy },
    { "eur", G_AWESOME_CODE_eur },
    { "euro", G_AWESOME_CODE_euro },
    { "exchange", G_AWESOME_CODE_exchange },
    { "exclamation", G_AWESOME_CODE_exclamation },
    { "exclamationcircle", G_AWESOME_CODE_exclamationcircle },
    { "exclamationtriangle", G_AWESOME_CODE_exclamationtriangle },
    { "expand", G_AWESOME_CODE_expand },
    { "expeditedssl", G_AWESOME_CODE_expeditedssl },
    { "externallink", G_AWESOME_CODE_externallink },
    { "externallinksquare", G_AWESOME_CODE_externallinksquare },
    { "eye", G_AWESOME_CODE_eye },
    { "eyeslash", G_AWESOME_CODE_eyeslash },
    { "eyedropper", G_AWESOME_CODE_eyedropper },
    { "fa", G_AWESOME_CODE_fa },
    { "facebook", G_AWESOME_CODE_facebook },
    { "facebookf", G_AWESOME_CODE_facebookf },
    { "facebookofficial", G_AWESOME_CODE_facebookofficial },
    { "facebooksquare", G_AWESOME_CODE_facebooksquare },
    { "fastbackward", G_AWESOME_CODE_fastbackward },
    { "fastforward", G_AWESOME_CODE_fastforward },
    { "fax", G_AWESOME_CODE_fax },
    { "feed", G_AWESOME_CODE_feed },
    { "female", G_AWESOME_CODE_female },
    { "fighterjet", G_AWESOME_CODE_fighterjet },
    { "file", G_AWESOME_CODE_file },
    { "filearchiveo", G_AWESOME_CODE_filearchiveo },
    { "fileaudioo", G_AWESOME_CODE_fileaudioo },
    { "filecodeo", G_AWESOME_CODE_filecodeo },
    { "fileexcelo", G_AWESOME_CODE_fileexcelo },
    { "fileimageo", G_AWESOME_CODE_fileimageo },
    { "filemovieo", G_AWESOME_CODE_filemovieo },
    { "fileo", G_AWESOME_CODE_fileo },
    { "filepdfo", G_AWESOME_CODE_filepdfo },
    { "filephotoo", G_AWESOME_CODE_filephotoo },
    { "filepictureo", G_AWESOME_CODE_filepictureo },
    { "filepowerpointo", G_AWESOME_CODE_filepowerpointo },
    { "filesoundo", G_AWESOME_CODE_filesoundo },
    { "filetext", G_AWESOME_CODE_filetext },
    { "filetexto", G_AWESOME_CODE_filetexto },
    { "filevideoo", G_AWESOME_CODE_filevideoo },
    { "filewordo", G_AWESOME_CODE_filewordo },
    { "filezipo", G_AWESOME_CODE_filezipo },
    { "fileso", G_AWESOME_CODE_fileso },
    { "film", G_AWESOME_CODE_film },
    { "filter", G_AWESOME_CODE_filter },
    { "fire", G_AWESOME_CODE_fire },
    { "fireextinguisher", G_AWESOME_CODE_fireextinguisher },
    { "firefox", G_AWESOME_CODE_firefox },
    { "firstorder", G_AWESOME_CODE_firstorder },
    { "flag", G_AWESOME_CODE_flag },
    { "flagcheckered", G_AWESOME_CODE_flagcheckered },
    { "flago", G_AWESOME_CODE_flago },
    { "flash", G_AWESOME_CODE_flash },
    { "flask", G_AWESOME_CODE_flask },
    { "flickr", G_AWESOME_CODE_flickr },
    { "floppyo", G_AWESOME_CODE_floppyo },
    { "folder", G_AWESOME_CODE_folder },
    { "foldero", G_AWESOME_CODE_foldero },
    { "folderopen", G_AWESOME_CODE_folderopen },
    { "folderopeno", G_AWESOME_CODE_folderopeno },
    { "font", G_AWESOME_CODE_font },
    { "fontawesome", G_AWESOME_CODE_fontawesome },
    { "fonticons", G_AWESOME_CODE_fonticons },
    { "fortawesome", G_AWESOME_CODE_fortawesome },
    { "forumbee", G_AWESOME_CODE_forumbee },
    { "forward", G_AWESOME_CODE_forward },
    { "foursquare", G_AWESOME_CODE_foursquare },
    { "freecodecamp", G_AWESOME_CODE_freecodecamp },
    { "frowno", G_AWESOME_CODE_frowno },
    { "futbolo", G_AWESOME_CODE_futbolo },
    { "gamepad", G_AWESOME_CODE_gamepad },
    { "gavel", G_AWESOME_CODE_gavel },
    { "gbp", G_AWESOME_CODE_gbp },
    { "ge", G_AWESOME_CODE_ge },
    { "gear", G_AWESOME_CODE_gear },
    { "gears", G_AWESOME_CODE_gears },
    { "genderless", G_AWESOME_CODE_genderless },
    { "getpocket", G_AWESOME_CODE_getpocket },
    { "gg", G_AWESOME_CODE_gg },
    { "ggcircle", G_AWESOME_CODE_ggcircle },
    { "gift", G_AWESOME_CODE_gift },
    { "git", G_AWESOME_CODE_git },
    { "gitsquare", G_AWESOME_CODE_gitsquare },
    { "github", G_AWESOME_CODE_github },
    { "githubalt", G_AWESOME_CODE_githubalt },
    { "githubsquare", G_AWESOME_CODE_githubsquare },
    { "gitlab", G_AWESOME_CODE_gitlab },
    { "gittip", G_AWESOME_CODE_gittip },
    { "glass", G_AWESOME_CODE_glass },
    { "glide", G_AWESOME_CODE_glide },
    { "glideg", G_AWESOME_CODE_glideg },
    { "globe", G_AWESOME_CODE_globe },
    { "google", G_AWESOME_CODE_google },
    { "googleplus", G_AWESOME_CODE_googleplus },
    { "googlepluscircle", G_AWESOME_CODE_googlepluscircle },
    { "googleplusofficial", G_AWESOME_CODE_googleplusofficial },
    { "googleplussquare", G_AWESOME_CODE_googleplussquare },
    { "googlewallet", G_AWESOME_CODE_googlewallet },
    { "graduationcap", G_AWESOME_CODE_graduationcap },
    { "gratipay", G_AWESOME_CODE_gratipay },
    { "grav", G_AWESOME_CODE_grav },
    { "group", G_AWESOME_CODE_group },
    { "hsquare", G_AWESOME_CODE_hsquare },
    { "hackernews", G_AWESOME_CODE_hackernews },
    { "handgrabo", G_AWESOME_CODE_handgrabo },
    { "handlizardo", G_AWESOME_CODE_handlizardo },
    { "handodown", G_AWESOME_CODE_handodown },
    { "handoleft", G_AWESOME_CODE_handoleft },
    { "handoright", G_AWESOME_CODE_handoright },
    { "handoup", G_AWESOME_CODE_handoup },
    { "handpapero", G_AWESOME_CODE_handpapero },
    { "handpeaceo", G_AWESOME_CODE_handpeaceo },
    { "handpointero", G_AWESOME_CODE_handpointero },
    { "handrocko", G_AWESOME_CODE_handrocko },
    { "handscissorso", G_AWESOME_CODE_handscissorso },
    { "handspocko", G_AWESOME_CODE_handspocko },
    { "handstopo", G_AWESOME_CODE_handstopo },
    { "handshakeo", G_AWESOME_CODE_handshakeo },
    { "hardofhearing", G_AWESOME_CODE_hardofhearing },
    { "hashtag", G_AWESOME_CODE_hashtag },
    { "hddo", G_AWESOME_CODE_hddo },
    { "header", G_AWESOME_CODE_header },
    { "headphones", G_AWESOME_CODE_headphones },
    { "heart", G_AWESOME_CODE_heart },
    { "hearto", G_AWESOME_CODE_hearto },
    { "heartbeat", G_AWESOME_CODE_heartbeat },
    { "history", G_AWESOME_CODE_history },
    { "home", G_AWESOME_CODE_home },
    { "hospitalo", G_AWESOME_CODE_hospitalo },
    { "hotel", G_AWESOME_CODE_hotel },
    { "hourglass", G_AWESOME_CODE_hourglass },
    { "hourglass1", G_AWESOME_CODE_hourglass1 },
    { "hourglass2", G_AWESOME_CODE_hourglass2 },
    { "hourglass3", G_AWESOME_CODE_hourglass3 },
    { "hourglassend", G_AWESOME_CODE_hourglassend },
    { "hourglasshalf", G_AWESOME_CODE_hourglasshalf },
    { "hourglasso", G_AWESOME_CODE_hourglasso },
    { "hourglassstart", G_AWESOME_CODE_hourglassstart },
    { "houzz", G_AWESOME_CODE_houzz },
    { "html5", G_AWESOME_CODE_html5 },
    { "icursor", G_AWESOME_CODE_icursor },
    { "idbadge", G_AWESOME_CODE_idbadge },
    { "idcard", G_AWESOME_CODE_idcard },
    { "idcardo", G_AWESOME_CODE_idcardo },
    { "ils", G_AWESOME_CODE_ils },
    { "image", G_AWESOME_CODE_image },
    { "imdb", G_AWESOME_CODE_imdb },
    { "inbox", G_AWESOME_CODE_inbox },
    { "indent", G_AWESOME_CODE_indent },
    { "industry", G_AWESOME_CODE_industry },
    { "info", G_AWESOME_CODE_info },
    { "infocircle", G_AWESOME_CODE_infocircle },
    { "inr", G_AWESOME_CODE_inr },
    { "instagram", G_AWESOME_CODE_instagram },
    { "institution", G_AWESOME_CODE_institution },
    { "internetexplorer", G_AWESOME_CODE_internetexplorer },
    { "intersex", G_AWESOME_CODE_intersex },
    { "ioxhost", G_AWESOME_CODE_ioxhost },
    { "italic", G_AWESOME_CODE_italic },
    { "joomla", G_AWESOME_CODE_joomla },
    { "jpy", G_AWESOME_CODE_jpy },
    { "jsfiddle", G_AWESOME_CODE_jsfiddle },
    { "key", G_AWESOME_CODE_key },
    { "keyboardo", G_AWESOME_CODE_keyboardo },
    { "krw", G_AWESOME_CODE_krw },
    { "language", G_AWESOME_CODE_language },
    { "laptop", G_AWESOME_CODE_laptop },
    { "lastfm", G_AWESOME_CODE_lastfm },
    { "lastfmsquare", G_AWESOME_CODE_lastfmsquare },
    { "leaf", G_AWESOME_CODE_leaf },
    { "leanpub", G_AWESOME_CODE_leanpub },
    { "legal", G_AWESOME_CODE_legal },
    { "lemono", G_AWESOME_CODE_lemono },
    { "leveldown", G_AWESOME_CODE_leveldown },
    { "levelup", G_AWESOME_CODE_levelup },
    { "lifebouy", G_AWESOME_CODE_lifebouy },
    { "lifebuoy", G_AWESOME_CODE_lifebuoy },
    { "lifering", G_AWESOME_CODE_lifering },
    { "lifesaver", G_AWESOME_CODE_lifesaver },
    { "lightbulbo", G_AWESOME_CODE_lightbulbo },
    { "linechart", G_AWESOME_CODE_linechart },
    { "link", G_AWESOME_CODE_link },
    { "linkedin", G_AWESOME_CODE_linkedin },
    { "linkedinsquare", G_AWESOME_CODE_linkedinsquare },
    { "linode", G_AWESOME_CODE_linode },
    { "fa_linux", G_AWESOME_CODE_fa_linux },
    { "list", G_AWESOME_CODE_list },
    { "listalt", G_AWESOME_CODE_listalt },
    { "listol", G_AWESOME_CODE_listol },
    { "listul", G_AWESOME_CODE_listul },
    { "locationarrow", G_AWESOME_CODE_locationarrow },
    { "lock", G_AWESOME_CODE_lock },
    { "longarrowdown", G_AWESOME_CODE_longarrowdown },
    { "longarrowleft", G_AWESOME_CODE_longarrowleft },
    { "longarrowright", G_AWESOME_CODE_longarrowright },
    { "longarrowup", G_AWESOME_CODE_longarrowup },
    { "lowvision", G_AWESOME_CODE_lowvision },
    { "magic", G_AWESOME_CODE_magic },
    { "magnet", G_AWESOME_CODE_magnet },
    { "mailforward", G_AWESOME_CODE_mailforward },
    { "mailreply", G_AWESOME_CODE_mailreply },
    { "mailreplyall", G_AWESOME_CODE_mailreplyall },
    { "male", G_AWESOME_CODE_male },
    { "map", G_AWESOME_CODE_map },
    { "mapmarker", G_AWESOME_CODE_mapmarker },
    { "mapo", G_AWESOME_CODE_mapo },
    { "mappin", G_AWESOME_CODE_mappin },
    { "mapsigns", G_AWESOME_CODE_mapsigns },
    { "mars", G_AWESOME_CODE_mars },
    { "marsdouble", G_AWESOME_CODE_marsdouble },
    { "marsstroke", G_AWESOME_CODE_marsstroke },
    { "marsstrokeh", G_AWESOME_CODE_marsstrokeh },
    { "marsstrokev", G_AWESOME_CODE_marsstrokev },
    { "maxcdn", G_AWESOME_CODE_maxcdn },
    { "meanpath", G_AWESOME_CODE_meanpath },
    { "medium", G_AWESOME_CODE_medium },
    { "medkit", G_AWESOME_CODE_medkit },
    { "meetup", G_AWESOME_CODE_meetup },
    { "meho", G_AWESOME_CODE_meho },
    { "mercury", G_AWESOME_CODE_mercury },
    { "microchip", G_AWESOME_CODE_microchip },
    { "microphone", G_AWESOME_CODE_microphone },
    { "microphoneslash", G_AWESOME_CODE_microphoneslash },
    { "minus", G_AWESOME_CODE_minus },
    { "minuscircle", G_AWESOME_CODE_minuscircle },
    { "minussquare", G_AWESOME_CODE_minussquare },
    { "minussquareo", G_AWESOME_CODE_minussquareo },
    { "mixcloud", G_AWESOME_CODE_mixcloud },
    { "mobile", G_AWESOME_CODE_mobile },
    { "mobilephone", G_AWESOME_CODE_mobilephone },
    { "modx", G_AWESOME_CODE_modx },
    { "money", G_AWESOME_CODE_money },
    { "moono", G_AWESOME_CODE_moono },
    { "mortarboard", G_AWESOME_CODE_mortarboard },
    { "motorcycle", G_AWESOME_CODE_motorcycle },
    { "mousepointer", G_AWESOME_CODE_mousepointer },
    { "music", G_AWESOME_CODE_music },
    { "navicon", G_AWESOME_CODE_navicon },
    { "neuter", G_AWESOME_CODE_neuter },
    { "newspapero", G_AWESOME_CODE_newspapero },
    { "objectgroup", G_AWESOME_CODE_objectgroup },
    { "objectungroup", G_AWESOME_CODE_objectungroup },
    { "odnoklassniki", G_AWESOME_CODE_odnoklassniki },
    { "odnoklassnikisquare", G_AWESOME_CODE_odnoklassnikisquare },
    { "opencart", G_AWESOME_CODE_opencart },
    { "openid", G_AWESOME_CODE_openid },
    { "opera", G_AWESOME_CODE_opera },
    { "optinmonster", G_AWESOME_CODE_optinmonster },
    { "outdent", G_AWESOME_CODE_outdent },
    { "pagelines", G_AWESOME_CODE_pagelines },
    { "paintbrush", G_AWESOME_CODE_paintbrush },
    { "paperplane", G_AWESOME_CODE_paperplane },
    { "paperplaneo", G_AWESOME_CODE_paperplaneo },
    { "paperclip", G_AWESOME_CODE_paperclip },
    { "paragraph", G_AWESOME_CODE_paragraph },
    { "paste", G_AWESOME_CODE_paste },
    { "pause", G_AWESOME_CODE_pause },
    { "pausecircle", G_AWESOME_CODE_pausecircle },
    { "pausecircleo", G_AWESOME_CODE_pausecircleo },
    { "paw", G_AWESOME_CODE_paw },
    { "paypal", G_AWESOME_CODE_paypal },
    { "pencil", G_AWESOME_CODE_pencil },
    { "pencilsquare", G_AWESOME_CODE_pencilsquare },
    { "pencilsquareo", G_AWESOME_CODE_pencilsquareo },
    { "percent", G_AWESOME_CODE_percent },
    { "phone", G_AWESOME_CODE_phone },
    { "phonesquare", G_AWESOME_CODE_phonesquare },
    { "photo", G_AWESOME_CODE_photo },
    { "pictureo", G_AWESOME_CODE_pictureo },
    { "piechart", G_AWESOME_CODE_piechart },
    { "piedpiper", G_AWESOME_CODE_piedpiper },
    { "piedpiperalt", G_AWESOME_CODE_piedpiperalt },
    { "piedpiperpp", G_AWESOME_CODE_piedpiperpp },
    { "pinterest", G_AWESOME_CODE_pinterest },
    { "pinterestp", G_AWESOME_CODE_pinterestp },
    { "pinterestsquare", G_AWESOME_CODE_pinterestsquare },
    { "plane", G_AWESOME_CODE_plane },
    { "play", G_AWESOME_CODE_play },
    { "playcircle", G_AWESOME_CODE_playcircle },
    { "playcircleo", G_AWESOME_CODE_playcircleo },
    { "plug", G_AWESOME_CODE_plug },
    { "plus", G_AWESOME_CODE_plus },
    { "pluscircle", G_AWESOME_CODE_pluscircle },
    { "plussquare", G_AWESOME_CODE_plussquare },
    { "plussquareo", G_AWESOME_CODE_plussquareo },
    { "podcast", G_AWESOME_CODE_podcast },
    { "poweroff", G_AWESOME_CODE_poweroff },
    { "print", G_AWESOME_CODE_print },
    { "producthunt", G_AWESOME_CODE_producthunt },
    { "puzzlepiece", G_AWESOME_CODE_puzzlepiece },
    { "qq", G_AWESOME_CODE_qq },
    { "qrcode", G_AWESOME_CODE_qrcode },
    { "question", G_AWESOME_CODE_question },
    { "questioncircle", G_AWESOME_CODE_questioncircle },
    { "questioncircleo", G_AWESOME_CODE_questioncircleo },
    { "quora", G_AWESOME_CODE_quora },
    { "quoteleft", G_AWESOME_CODE_quoteleft },
    { "quoteright", G_AWESOME_CODE_quoteright },
    { "ra", G_AWESOME_CODE_ra },
    { "random", G_AWESOME_CODE_random },
    { "ravelry", G_AWESOME_CODE_ravelry },
    { "rebel", G_AWESOME_CODE_rebel },
    { "recycle", G_AWESOME_CODE_recycle },
    { "reddit", G_AWESOME_CODE_reddit },
    { "redditalien", G_AWESOME_CODE_redditalien },
    { "redditsquare", G_AWESOME_CODE_redditsquare },
    { "refresh", G_AWESOME_CODE_refresh },
    { "registered", G_AWESOME_CODE_registered },
    { "remove", G_AWESOME_CODE_remove },
    { "renren", G_AWESOME_CODE_renren },
    { "reorder", G_AWESOME_CODE_reorder },
    { "repeat", G_AWESOME_CODE_repeat },
    { "reply", G_AWESOME_CODE_reply },
    { "replyall", G_AWESOME_CODE_replyall },
    { "resistance", G_AWESOME_CODE_resistance },
    { "retweet", G_AWESOME_CODE_retweet },
    { "rmb", G_AWESOME_CODE_rmb },
    { "road", G_AWESOME_CODE_road },
    { "rocket", G_AWESOME_CODE_rocket },
    { "rotateleft", G_AWESOME_CODE_rotateleft },
    { "rotateright", G_AWESOME_CODE_rotateright },
    { "rouble", G_AWESOME_CODE_rouble },
    { "rss", G_AWESOME_CODE_rss },
    { "rsssquare", G_AWESOME_CODE_rsssquare },
    { "rub", G_AWESOME_CODE_rub },
    { "ruble", G_AWESOME_CODE_ruble },
    { "rupee", G_AWESOME_CODE_rupee },
    { "s15", G_AWESOME_CODE_s15 },
    { "safari", G_AWESOME_CODE_safari },
    { "save", G_AWESOME_CODE_save },
    { "scissors", G_AWESOME_CODE_scissors },
    { "scribd", G_AWESOME_CODE_scribd },
    { "search", G_AWESOME_CODE_search },
    { "searchminus", G_AWESOME_CODE_searchminus },
    { "searchplus", G_AWESOME_CODE_searchplus },
    { "sellsy", G_AWESOME_CODE_sellsy },
    { "send", G_AWESOME_CODE_send },
    { "sendo", G_AWESOME_CODE_sendo },
    { "server", G_AWESOME_CODE_server },
    { "share", G_AWESOME_CODE_share },
    { "sharealt", G_AWESOME_CODE_sharealt },
    { "sharealtsquare", G_AWESOME_CODE_sharealtsquare },
    { "sharesquare", G_AWESOME_CODE_sharesquare },
    { "sharesquareo", G_AWESOME_CODE_sharesquareo },
    { "shekel", G_AWESOME_CODE_shekel },
    { "sheqel", G_AWESOME_CODE_sheqel },
    { "shield", G_AWESOME_CODE_shield },
    { "ship", G_AWESOME_CODE_ship },
    { "shirtsinbulk", G_AWESOME_CODE_shirtsinbulk },
    { "shoppingbag", G_AWESOME_CODE_shoppingbag },
    { "shoppingbasket", G_AWESOME_CODE_shoppingbasket },
    { "shoppingcart", G_AWESOME_CODE_shoppingcart },
    { "shower", G_AWESOME_CODE_shower },
    { "signin", G_AWESOME_CODE_signin },
    { "signlanguage", G_AWESOME_CODE_signlanguage },
    { "signout", G_AWESOME_CODE_signout },
    { "signal", G_AWESOME_CODE_signal },
    { "signing", G_AWESOME_CODE_signing },
    { "simplybuilt", G_AWESOME_CODE_simplybuilt },
    { "sitemap", G_AWESOME_CODE_sitemap },
    { "skyatlas", G_AWESOME_CODE_skyatlas },
    { "skype", G_AWESOME_CODE_skype },
    { "slack", G_AWESOME_CODE_slack },
    { "sliders", G_AWESOME_CODE_sliders },
    { "slideshare", G_AWESOME_CODE_slideshare },
    { "smileo", G_AWESOME_CODE_smileo },
    { "snapchat", G_AWESOME_CODE_snapchat },
    { "snapchatghost", G_AWESOME_CODE_snapchatghost },
    { "snapchatsquare", G_AWESOME_CODE_snapchatsquare },
    { "snowflakeo", G_AWESOME_CODE_snowflakeo },
    { "soccerballo", G_AWESOME_CODE_soccerballo },
    { "sort", G_AWESOME_CODE_sort },
    { "sortalphaasc", G_AWESOME_CODE_sortalphaasc },
    { "sortalphadesc", G_AWESOME_CODE_sortalphadesc },
    { "sortamountasc", G_AWESOME_CODE_sortamountasc },
    { "sortamountdesc", G_AWESOME_CODE_sortamountdesc },
    { "sortasc", G_AWESOME_CODE_sortasc },
    { "sortdesc", G_AWESOME_CODE_sortdesc },
    { "sortdown", G_AWESOME_CODE_sortdown },
    { "sortnumericasc", G_AWESOME_CODE_sortnumericasc },
    { "sortnumericdesc", G_AWESOME_CODE_sortnumericdesc },
    { "sortup", G_AWESOME_CODE_sortup },
    { "soundcloud", G_AWESOME_CODE_soundcloud },
    { "spaceshuttle", G_AWESOME_CODE_spaceshuttle },
    { "spinner", G_AWESOME_CODE_spinner },
    { "spoon", G_AWESOME_CODE_spoon },
    { "spotify", G_AWESOME_CODE_spotify },
    { "square", G_AWESOME_CODE_square },
    { "squareo", G_AWESOME_CODE_squareo },
    { "stackexchange", G_AWESOME_CODE_stackexchange },
    { "stackoverflow", G_AWESOME_CODE_stackoverflow },
    { "star", G_AWESOME_CODE_star },
    { "starhalf", G_AWESOME_CODE_starhalf },
    { "starhalfempty", G_AWESOME_CODE_starhalfempty },
    { "starhalffull", G_AWESOME_CODE_starhalffull },
    { "starhalfo", G_AWESOME_CODE_starhalfo },
    { "staro", G_AWESOME_CODE_staro },
    { "steam", G_AWESOME_CODE_steam },
    { "steamsquare", G_AWESOME_CODE_steamsquare },
    { "stepbackward", G_AWESOME_CODE_stepbackward },
    { "stepforward", G_AWESOME_CODE_stepforward },
    { "stethoscope", G_AWESOME_CODE_stethoscope },
    { "stickynote", G_AWESOME_CODE_stickynote },
    { "stickynoteo", G_AWESOME_CODE_stickynoteo },
    { "stop", G_AWESOME_CODE_stop },
    { "stopcircle", G_AWESOME_CODE_stopcircle },
    { "stopcircleo", G_AWESOME_CODE_stopcircleo },
    { "streetview", G_AWESOME_CODE_streetview },
    { "strikethrough", G_AWESOME_CODE_strikethrough },
    { "stumbleupon", G_AWESOME_CODE_stumbleupon },
    { "stumbleuponcircle", G_AWESOME_CODE_stumbleuponcircle },
    { "subscript", G_AWESOME_CODE_subscript },
    { "subway", G_AWESOME_CODE_subway },
    { "suitcase", G_AWESOME_CODE_suitcase },
    { "suno", G_AWESOME_CODE_suno },
    { "superpowers", G_AWESOME_CODE_superpowers },
    { "superscript", G_AWESOME_CODE_superscript },
    { "support", G_AWESOME_CODE_support },
    { "table", G_AWESOME_CODE_table },
    { "tablet", G_AWESOME_CODE_tablet },
    { "tachometer", G_AWESOME_CODE_tachometer },
    { "tag", G_AWESOME_CODE_tag },
    { "tags", G_AWESOME_CODE_tags },
    { "tasks", G_AWESOME_CODE_tasks },
    { "taxi", G_AWESOME_CODE_taxi },
    { "telegram", G_AWESOME_CODE_telegram },
    { "television", G_AWESOME_CODE_television },
    { "tencentweibo", G_AWESOME_CODE_tencentweibo },
    { "terminal", G_AWESOME_CODE_terminal },
    { "textheight", G_AWESOME_CODE_textheight },
    { "textwidth", G_AWESOME_CODE_textwidth },
    { "th", G_AWESOME_CODE_th },
    { "thlarge", G_AWESOME_CODE_thlarge },
    { "thlist", G_AWESOME_CODE_thlist },
    { "themeisle", G_AWESOME_CODE_themeisle },
    { "thermometer", G_AWESOME_CODE_thermometer },
    { "thermometer0", G_AWESOME_CODE_thermometer0 },
    { "thermometer1", G_AWESOME_CODE_thermometer1 },
    { "thermometer2", G_AWESOME_CODE_thermometer2 },
    { "thermometer3", G_AWESOME_CODE_thermometer3 },
    { "thermometer4", G_AWESOME_CODE_thermometer4 },
    { "thermometerempty", G_AWESOME_CODE_thermometerempty },
    { "thermometerfull", G_AWESOME_CODE_thermometerfull },
    { "thermometerhalf", G_AWESOME_CODE_thermometerhalf },
    { "thermometerquarter", G_AWESOME_CODE_thermometerquarter },
    { "thermometerthreequarters", G_AWESOME_CODE_thermometerthreequarters },
    { "thumbtack", G_AWESOME_CODE_thumbtack },
    { "thumbsdown", G_AWESOME_CODE_thumbsdown },
    { "thumbsodown", G_AWESOME_CODE_thumbsodown },
    { "thumbsoup", G_AWESOME_CODE_thumbsoup },
    { "thumbsup", G_AWESOME_CODE_thumbsup },
    { "ticket", G_AWESOME_CODE_ticket },
    { "times", G_AWESOME_CODE_times },
    { "timescircle", G_AWESOME_CODE_timescircle },
    { "timescircleo", G_AWESOME_CODE_timescircleo },
    { "timesrectangle", G_AWESOME_CODE_timesrectangle },
    { "timesrectangleo", G_AWESOME_CODE_timesrectangleo },
    { "tint", G_AWESOME_CODE_tint },
    { "toggledown", G_AWESOME_CODE_toggledown },
    { "toggleleft", G_AWESOME_CODE_toggleleft },
    { "toggleoff", G_AWESOME_CODE_toggleoff },
    { "toggleon", G_AWESOME_CODE_toggleon },
    { "toggleright", G_AWESOME_CODE_toggleright },
    { "toggleup", G_AWESOME_CODE_toggleup },
    { "trademark", G_AWESOME_CODE_trademark },
    { "train", G_AWESOME_CODE_train },
    { "transgender", G_AWESOME_CODE_transgender },
    { "transgenderalt", G_AWESOME_CODE_transgenderalt },
    { "trash", G_AWESOME_CODE_trash },
    { "trasho", G_AWESOME_CODE_trasho },
    { "tree", G_AWESOME_CODE_tree },
    { "trello", G_AWESOME_CODE_trello },
    { "tripadvisor", G_AWESOME_CODE_tripadvisor },
    { "trophy", G_AWESOME_CODE_trophy },
    { "truck", G_AWESOME_CODE_truck },
    { "fa_try", G_AWESOME_CODE_fa_try },
    { "tty", G_AWESOME_CODE_tty },
    { "tumblr", G_AWESOME_CODE_tumblr },
    { "tumblrsquare", G_AWESOME_CODE_tumblrsquare },
    { "turkishlira", G_AWESOME_CODE_turkishlira },
    { "tv", G_AWESOME_CODE_tv },
    { "twitch", G_AWESOME_CODE_twitch },
    { "twitter", G_AWESOME_CODE_twitter },
    { "twittersquare", G_AWESOME_CODE_twittersquare },
    { "umbrella", G_AWESOME_CODE_umbrella },
    { "underline", G_AWESOME_CODE_underline },
    { "undo", G_AWESOME_CODE_undo },
    { "universalaccess", G_AWESOME_CODE_universalaccess },
    { "university", G_AWESOME_CODE_university },
    { "unlink", G_AWESOME_CODE_unlink },
    { "unlock", G_AWESOME_CODE_unlock },
    { "unlockalt", G_AWESOME_CODE_unlockalt },
    { "unsorted", G_AWESOME_CODE_unsorted },
    { "upload", G_AWESOME_CODE_upload },
    { "usb", G_AWESOME_CODE_usb },
    { "usd", G_AWESOME_CODE_usd },
    { "user", G_AWESOME_CODE_user },
    { "usercircle", G_AWESOME_CODE_usercircle },
    { "usercircleo", G_AWESOME_CODE_usercircleo },
    { "usermd", G_AWESOME_CODE_usermd },
    { "usero", G_AWESOME_CODE_usero },
    { "userplus", G_AWESOME_CODE_userplus },
    { "usersecret", G_AWESOME_CODE_usersecret },
    { "usertimes", G_AWESOME_CODE_usertimes },
    { "users", G_AWESOME_CODE_users },
    { "vcard", G_AWESOME_CODE_vcard },
    { "vcardo", G_AWESOME_CODE_vcardo },
    { "venus", G_AWESOME_CODE_venus },
    { "venusdouble", G_AWESOME_CODE_venusdouble },
    { "venusmars", G_AWESOME_CODE_venusmars },
    { "viacoin", G_AWESOME_CODE_viacoin },
    { "viadeo", G_AWESOME_CODE_viadeo },
    { "viadeosquare", G_AWESOME_CODE_viadeosquare },
    { "videocamera", G_AWESOME_CODE_videocamera },
    { "vimeo", G_AWESOME_CODE_vimeo },
    { "vimeosquare", G_AWESOME_CODE_vimeosquare },
    { "vine", G_AWESOME_CODE_vine },
    { "vk", G_AWESOME_CODE_vk },
    { "volumecontrolphone", G_AWESOME_CODE_volumecontrolphone },
    { "volumedown", G_AWESOME_CODE_volumedown },
    { "volumeoff", G_AWESOME_CODE_volumeoff },
    { "volumeup", G_AWESOME_CODE_volumeup },
    { "warning", G_AWESOME_CODE_warning },
    { "wechat", G_AWESOME_CODE_wechat },
    { "weibo", G_AWESOME_CODE_weibo },
    { "weixin", G_AWESOME_CODE_weixin },
    { "whatsapp", G_AWESOME_CODE_whatsapp },
    { "wheelchair", G_AWESOME_CODE_wheelchair },
    { "wheelchairalt", G_AWESOME_CODE_wheelchairalt },
    { "wifi", G_AWESOME_CODE_wifi },
    { "wikipediaw", G_AWESOME_CODE_wikipediaw },
    { "windowclose", G_AWESOME_CODE_windowclose },
    { "windowcloseo", G_AWESOME_CODE_windowcloseo },
    { "windowmaximize", G_AWESOME_CODE_windowmaximize },
    { "windowminimize", G_AWESOME_CODE_windowminimize },
    { "windowrestore", G_AWESOME_CODE_windowrestore },
    { "windows", G_AWESOME_CODE_windows },
    { "won", G_AWESOME_CODE_won },
    { "wordpress", G_AWESOME_CODE_wordpress },
    { "wpbeginner", G_AWESOME_CODE_wpbeginner },
    { "wpexplorer", G_AWESOME_CODE_wpexplorer },
    { "wpforms", G_AWESOME_CODE_wpforms },
    { "wrench", G_AWESOME_CODE_wrench },
    { "xing", G_AWESOME_CODE_xing },
    { "xingsquare", G_AWESOME_CODE_xingsquare },
    { "ycombinator", G_AWESOME_CODE_ycombinator },
    { "ycombinatorsquare", G_AWESOME_CODE_ycombinatorsquare },
    { "yahoo", G_AWESOME_CODE_yahoo },
    { "yc", G_AWESOME_CODE_yc },
    { "ycsquare", G_AWESOME_CODE_ycsquare },
    { "yelp", G_AWESOME_CODE_yelp },
    { "yen", G_AWESOME_CODE_yen },
    { "yoast", G_AWESOME_CODE_yoast },
    { "youtube", G_AWESOME_CODE_youtube },
    { "youtubeplay", G_AWESOME_CODE_youtubeplay },
    { "youtubesquare", G_AWESOME_CODE_youtubesquare }
};
